bump ghc-typelits-knownnat
Otherwise there is an error in
```
[ 7 of 48] Compiling CLaSH.Promoted.Nat ( src/CLaSH/Promoted/Nat.hs, dist/build/CLaSH/Promoted/Nat.o )

src/CLaSH/Promoted/Nat.hs:186:21: error:
    ? Could not deduce (KnownNat a) arising from a use of ?SNat?
      from the context: KnownNat (a + b)
```